global using Microsoft.Extensions.AI;
global using OllamaSharp;
global using OpenAI;
global using Spectre.Console;
global using System.ClientModel;
global using Microsoft.Extensions.DependencyInjection;
global using Workshops.KernelAi.ConsoleApp.Domain;
global using Workshops.KernelAi.ConsoleApp.Helpers;
global using Workshops.KernelAi.ConsoleApp.Settings;